### ISSUE TITLE
Nested-Loop Joins: Contradiction between Assignment 7 solutions and Lecture 17?

### ISSUE THREAD

**Issue by Jiangyi** [rwongone/ece356#1]
Lecture 17 states that in the worst case scenario of nested-loop joins:
```
the total amount of seeks is 2 * b1 and the number of blocks to be transferred is b1 + n1 ×b2.
```
However, solutions to question 12.3a on assignment 7 states the number of seeks as effectively n1 + b1.

Which of the two is correct? Thank you!

**Comment by jzarnett** [comment]
b_1 + n_1 is correct. Lecture notes have been corrected.

**Comment by Jiangyi** [comment]
Thank you!
